

###########   PRODUCTS BY SEARCH   ########

GET http://localhost:5000/products



###########   PRODUCTS BY CATEGORY   ########
GET http://localhost:5000/products/electronics



############    PRODUCTS BY CATEGOEY AND ID    ##########
GET http://localhost:5000/products/electronics/5fda124ef08b7d0f6c2475ba/



####################   create Product review    #######################
POST http://localhost:5000/products/electronics/5fda124ef08b7d0f6c2475ba/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDYzNTcwZjcyNDRlMWI3ODZiMGJjMCIsImlhdCI6MTYxNTIxMzk5NiwiZXhwIjoxNjE1MjE3NTk2fQ.6mGqIXBK815NXgHPj9rm_e3TiCFawbSSI5gk5o7O0rE

{
      "rating": "10",
      "comment": "Omaagoo turu love"
}



#################   Product delete    #################################
DELETE http://localhost:5000/products/electronics/5fda124ef08b7d0f6c2475c0/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNTM5Mjc4MiwiZXhwIjoxNjE2MjU2NzgyfQ.ggtdTg_JHyFmDYd-IqM6Py31IACLG0C13FRij64Tz_4


################   POST new product  #################################
POST http://localhost:5000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNTM5Mjc4MiwiZXhwIjoxNjE2MjU2NzgyfQ.ggtdTg_JHyFmDYd-IqM6Py31IACLG0C13FRij64Tz_4

#   {
#     "price": 49.99,
#     "countInStock": 7,
#     "numReviews": 2,
#     "rating": 2.5,
#     "_id": "5fda124ef08b7d0f6c2475be",
#     "name": "Logitech G-Series Gaming Mouse",
#     "image": "/assets/images/electronics/mouse.jpg",
#     "description": "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
#     "brand": "Logitech",
#     "category": "electronics",
#     "user": "5fda124ef08b7d0f6c2475b6",
#     "reviews": [
#       {
#         "rating": 4,
#         "_id": "601b81fe71198234800344bc",
#         "name": "Saaho Dutta",
#         "comment": "nunu kata",
#         "user": "5fe5a236726d4d0c84f2f659",
#         "createdAt": "2021-02-04T05:11:26.478Z",
#         "updatedAt": "2021-02-04T05:11:26.478Z"
#       }
#     ],
#     "__v": 2,
#     "createdAt": "2020-12-16T13:57:34.230Z",
#     "updatedAt": "2021-02-04T05:23:23.304Z"
#   }




################  Auth Check  ########################

GET http://localhost:5000/user/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNjA3MTYzOSwiZXhwIjoxNjE2MDcxNjY5fQ.Z688fjFmBNU7LuJUxNSaU-me1g4OTHCk5Y-xTe3OdDM


#######################     LOGIN   ####################
POST http://localhost:5000/user/login
Content-Type: application/json

{
      "email": "mita@gmail.com",
      "password": "user12345"
}



#####################   REGSITER    #####################
POST http://localhost:5000/user/register
Content-Type: application/json

{
      "name": "test",
      "email": "test@gmail.com",
      "password": "user1234"
}



########################   PROFILE  #####################
GET http://localhost:5000/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNTM5Mjc4MiwiZXhwIjoxNjE2MjU2NzgyfQ.ggtdTg_JHyFmDYd-IqM6Py31IACLG0C13FRij64Tz_4



########################   GET all users (for admin)   ##########
GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNTM5Mjc4MiwiZXhwIjoxNjE2MjU2NzgyfQ.ggtdTg_JHyFmDYd-IqM6Py31IACLG0C13FRij64Tz_4



########################   GET user by id (for admin)   ##########
GET http://localhost:5000/user/601b6f8f490cf240a814590a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNTM5Mjc4MiwiZXhwIjoxNjE2MjU2NzgyfQ.ggtdTg_JHyFmDYd-IqM6Py31IACLG0C13FRij64Tz_4



########################   DELETE user by id (for admin)   ##########
DELETE http://localhost:5000/user/602f3baee941690004f131a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNTM5Mjc4MiwiZXhwIjoxNjE2MjU2NzgyfQ.ggtdTg_JHyFmDYd-IqM6Py31IACLG0C13FRij64Tz_4


######################   UPDATE user by id (for admin)  #############
PUT http://localhost:5000/user/6048f18caa96ca40441615cb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNTM5Mjc4MiwiZXhwIjoxNjE2MjU2NzgyfQ.ggtdTg_JHyFmDYd-IqM6Py31IACLG0C13FRij64Tz_4

{
      "isAdmin": true,
      "name": "test2"
}




##################   FORGET PASSWORD   ########################


########   email verification  ##########
POST http://localhost:5000/user/email-verify
Content-Type: application/json

{
      "email": "mita@gmail.com"
}


########  reset password   #########
POST http://localhost:5000/user/reset-password/5fd82c40-0bae-4442-8fef-630de800169a
Content-Type: application/json

{
      "password": "user12345"
}

#########################  ORDERS BY ID    ##################
GET http://localhost:5000/orders/5fed5fdb7073bf0b6ce37038
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjYwNDYzNTcwZjcyNDRlMWI3ODZiMGJjMCIsImlhdCI6MTYxNTIyNTYzMCwiZXhwIjoxNjQ2NzgzMjMwfSwiaWF0IjoxNjE1MjI4NDkzLCJleHAiOjE2MTUyMjg1MjN9.rIXB9uySIufe4yNI7Xp9M9eG_tr8K0IoWYnYFoXvCfc



#######################   PAYPAL CONFIG  #####################
GET http://localhost:5000/config/paypal



######################   LOGGED IN USER ORDERS (paid)   #############
GET http://localhost:5000/orders/myorders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTVhMjM2NzI2ZDRkMGM4NGYyZjY1OSIsImlhdCI6MTYxNTIxMTMwMSwiZXhwIjoxNjE1MjE0OTAxfQ.gTTicFfLdipDV2SbEGSBmVfTK2tEgv5yr3nu1w4vnss



######################   ALL ORDERS (for admin user)   #############
GET http://localhost:5000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTI1MDZmNWE5MDI0MDU3OGYwY2MxMCIsImlhdCI6MTYxNTM5Mjc4MiwiZXhwIjoxNjE2MjU2NzgyfQ.ggtdTg_JHyFmDYd-IqM6Py31IACLG0C13FRij64Tz_4
