export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED";
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAILED = "ORDER_PAY_FAILED";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const LIST_MY_ORDER_REQUEST = "LIST_MY_ORDER_REQUEST";
export const LIST_MY_ORDER_SUCCESS = "LIST_MY_ORDER_SUCCESS";
export const LIST_MY_ORDER_FAILED = "LIST_MY_ORDER_FAILED";
export const LIST_MY_ORDER_RESET = "LIST_MY_ORDER_RESET";

export const LIST_ALL_ORDER_REQUEST = "LIST_ALL_ORDER_REQUEST";
export const LIST_ALL_ORDER_SUCCESS = "LIST_ALL_ORDER_SUCCESS";
export const LIST_ALL_ORDER_FAILED = "LIST_ALL_ORDER_FAILED";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAILED = "ORDER_DELIVER_FAILED";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
