#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing to skip add --no-verify at end'


npm run format || 
(
        echo 'Something might be messed up while formatting';
        
        false;
)

npm run lint:fix ||
(
        echo 'Something might be messed up while linting';
        
        false;
)


# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
